# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=crlf"]
  - repo: local
    hooks:
      - id: check-large-files
        name: Check Large Files
        entry: python .pre-commit-hooks/check-large-files.py
        args: ["--maxkb=225"]
        language: system

      - id: unify
        name: unify
        entry: unify --in-place
        language: system
        types: [python]

      - id: yapf-isort
        name: Run yapf + isort
        description: Let yapf format your python code but isort sort your imports.
        entry: .pre-commit-hooks/yapf-isort.ps1
        language: system
        files: \.py$

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]

      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]

      - id: pytest
        name: Run Tests
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

exclude: |
    (?x)^(
        .*.excalidraw|
        .pre-commit-hooks/yapf-isort.sh
    )$
